### ISSUE TITLE
Should we merge mvt_provider and proviers config options.

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola-postgis#4]
Should be remove mvt_provider, and have the provider register it's self as an mvt type of provider. 

i.e.
```toml
[[mvtproviders]]
name = "test_postgis"       # provider name is referenced from map layers (required)
type = "postgis_mvt"            # the type of data provider must be "postgis" for this data provider (required)
host = "localhost"          # PostGIS database host (required)
port = 5432                 # PostGIS database port (required)
database = "tegola"         # PostGIS database name (required)
user = "tegola"             # PostGIS database user (required)
password = ""               # PostGIS database password (required)
```

There are some things to note about this approach.

1. The provider needs to that it's an MVT provider (this could be done by look to see if it supports the mvt_provider interface)

2. Documentation can be confusing as mvt providers can not conflate with other providers.
